### ISSUE TITLE
Enabling smsi in BAS

### ISSUE THREAD

**Issue by andrewlunde** [saphanaacademy/ServiceManagement#1]
Open a terminal.

cd ~
curl -o ServiceManagement.linux64 https://github.com/saphanaacademy/ServiceManagement/releases/download/v1.0.0/ServiceManagement.linux64
chmod +x ServiceManagement.linux64
cf install-plugin ServiceManagement.linux64

Now use it to dump the SMSI credentials as json.

cf s | grep service-manager

cf smsi CAPMT_SMC -credentials -json | tr -d '\n'

Reformat it like this.

        {
            "name": "CAPMT_SMC0",
            "dialect": "SAPHana",
            "server": "833726c5-cca3-4dce-a325-4385426009e7.hana.trial-us10.hanacloud.ondemand.com",
            "port": 443,
            "database": "730A518DDE484D299E306D794EE7BABB",
            "username": "730A518DDE484D299E306D794EE7BABB_91YNF0DT7UUIGLKMI4BBB6SLH_RT",
            "password": "Xi1tQLBYmK5DqcChUtsMrVMj7ylN.vKStBE-vD1LpYfHEiknEEunTU8rADrn7kwxk1xajXkaVwI9n.8gOsws1xKUwb-UB83vcaxKz6Y7skLSZZdy1coMpfwYO3QGG1cF",
            "askForPassword": false,
            "connectionTimeout": 30,
            "hanaOptions": {
                "encrypt": true,
                "sslValidateCertificate": true,
                "sslCryptoProvider": "openssl",
                "sslTrustStore": "-----BEGIN CERTIFICATE-----MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsBCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7PT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbRTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUwDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/EsrhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJFPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0lsYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQkCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=-----END CERTIFICATE-----"
            }
        }

Add it to the settings.json "sqltools.connections": [ ].

Boom! SQLTools connection to SM created HDI container in BAS.

BTW this file resides at:

/home/user/.theia/settings.json

**Comment by saphanaacademy** [comment]
Support for SQLTools format added in v1.0.1 via `-o sqltools` flag.
Install very simple once plugin added to CF community -this is ongoing.
