### ISSUE TITLE
Documentation update needed. 

### ISSUE THREAD

**Issue by alperdedeoglu** [saphanaacademy/ServiceManagement#3]
**cf install-plugin ServiceManagement** is not working, when we install the plugin from community repository. Which makes sense because the original name of plugin is  currently "service-management".

Also there are uninstall commands which needs to be updated.

Could you update the documentation like that?

Thanks.

**Comment by saphanaacademy** [comment]
Sorry about that. This plugin has been superseded by [https://github.com/SAP/cf-cli-smsi-plugin](url) which is available in the CF Community - please use that one instead. Thanks.
